### ISSUE TITLE
xpfm for xilinx_v1_ipu_202020_1

### ISSUE THREAD

**Issue by AEW2015** [AMDResearch/Riallto#22]
Do you know where I can find the file for this: --platform xilinx_v1_ipu_202020_1?

Thanks

**Comment by AEW2015** [comment]
I would like to use the Vitis GUI which provides a powerful tool to design and debug AIE-ML workloads.  It seems silly if you are already using the tool to provide compiling for the system to not give designers access to the GUI for it.

**Comment by schelleg** [comment]
I'm not familiar with that file.  Right now, Vitis does not support NPU development.

**Comment by AEW2015** [comment]
Thanks for the reply.
The xclbin files come from Vitis (v++) and you use Vitis to modify the AIE-MLs in your tools from the CLI.
https://github.com/AMDResearch/Riallto/blob/main/scripts/wsl/mlir_settings.sh
https://github.com/AMDResearch/Riallto/blob/main/scripts/wsl/setup_env.sh

**Comment by schelleg** [comment]
closing issue if no more discussion on Riallto topics ...

looks like further details on request/answers here: https://github.com/amd/xdna-driver/issues/8
